type: object
properties:
  templateId:
    type: string
    format: uuid
  showPagination:
    type: boolean
    default: true
  priceFormat:
    $ref: ./PriceFormat.yaml
  feesFormat:
    $ref: ./FeesFormat.yaml
  feesPayer:
    $ref: ../FeesPayer.yaml
  theming:
    $ref: ./theming/Theming.yaml
