type: string
enum:
  - STUDY
  - ESTIMATION
  - MARKET_STUDY
  - MARKET_ANALYSIS
  - VALUATION
  - PROPERTY
  - PRIVATE_PROPERTY
  - PROPERTY_ANALYTIC
  - PROPERTY_INDICATOR
  - SIMILAR_PROPERTY
  - SIMILAR_PROPERTY_ANALYTIC
  - PROGRAM
  - PROGRAM_ANALYTIC
  - ESTIMATE
  - MAPS
  - GEOGRAPHY
  - SOCIO_ECONOMIC
  - SEARCH_PROFESSIONAL
  - BUILDING_PERMIT
  - RENT_CONTROL
  - OPPORTUNITY
  - INVEST_STUDY
example: PROPERTY
