type: object
properties:
  type:
    $ref: ./ProductType.yaml
  marketingTypes:
    type: array
    items:
      $ref: ./MarketingType.yaml
  modules:
    type: array
    items:
      $ref: ./Module.yaml
  sources:
    type: array
    items:
      $ref: ./Source.yaml
  toggleFeatures:
    type: array
    items:
      $ref: ./ToggleFeature.yaml
  commercialZone:
    $ref: ./CommercialZone.yaml
  dealer:
    $ref: ./ProductDealer.yaml
