type: object
properties:
  active:
    type: boolean
  admin:
    type: boolean
  roles:
    type: array
    items:
      $ref: ./User-Role.yaml
    description: |
      - `CONSULTANT` : obsolète, utiliser `USER`.
      - `ASSISTANT` : obsolète, utiliser `USER`.
  emailChecked:
    type: boolean
  authenticationModes:
    type: array
    items:
      $ref: ./AuthenticationMode.yaml
