type: object
properties:
  active:
    type: boolean
  admin:
    type: boolean
  roles:
    type: array
    items:
      $ref: ./User-Role.yaml
  emailChecked:
    type: boolean
  backOfficeModules:
    type: array
    items:
      type: string
