name: Test and deploy release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3

      - name: Install OpenAPI
        run: npm install -g @redocly/cli@1.34.5

      - name: Generate doc
        run: openapi bundle src/openapi.yaml -o dist/openapi.yaml

      - name: GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_WWW_AUTOMATION_CREDENTIALS }}

      - name: Upload file
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ./dist/openapi.yaml
          destination: yanport-www.appspot.com

      - name: Notify Slack deploy
        if: always()
        run: python3 .github/scripts/notify-slack-deploy.py ${{ secrets.SLACK_TOKEN }} $TIMESTAMP ${{ job.status }} $GITHUB_RUN_ID $GITHUB_ACTOR
